version: "3.9"

services:
  web:
    build: ./web
    container_name: web_service
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    environment:
      - REDIS_HOST=cache
      - POSTGRES_HOST=db

  db:
    image: postgres:15
    container_name: db_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:7
    container_name: cache_service

volumes:
  pgdata:
